version: '2.4'
services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    network_mode: "host"
    volumes:
      - type: "bind"
        source: "./config.json"
        target: "/etc/v2ray/config.json"